vim.keymap.set('n', '<M-T>', ':InitPartial<CR>"+p<CR>')
vim.keymap.set('n', '<M-P>', ':InitPropousal<CR>"+p<CR>')
vim.keymap.set('n', '<M-Q>', ':InitTestItem<CR>"+p<CR>')
vim.keymap.set('n', '<M-M>', ':InitMain<CR>"+p<CR>')
vim.keymap.set('n', '<M-S>', ':InitText<CR>"+p<CR>')
vim.keymap.set('n', '<M-E>', ':InitBookExercise<CR>"+p<CR>')
vim.keymap.set('n', '<M-F>', ':InitArtFicha<CR>"+p<CR>')
