return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = {
      enable = true,
      disable = { "latex" },
    },
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "csv",
      "diff",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "latex",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vimdoc",
      "xml",
      "yaml",
    },
    sync_install = true,
    auto_install = true,
  },
}
